init outline auth
COSSAS/SOARCA-GUI pull request #60
Opened 2024-09-17 15:46 UTC by RabbITCybErSeC

2024-10-10 18:34 UTC, MaartendeKruijf requested changes

2024-10-10 18:34 UTC, MaartendeKruijf commented on .env.example
> +SOARCA_GUI_URI: http://localhost:8081
Maybe include port not in this URL as you have the port variable already

2024-10-10 18:34 UTC, MaartendeKruijf commented on auth/auth.go
> +	OIDC_CALL_BACK_PATH          = "/oidc-callback"
Maybe make this optional variables as well, this to allow the user to set a path.

2024-10-10 18:34 UTC, MaartendeKruijf commented on auth/auth.go
> +	COOKIE_SECRET_KEY_LENGHT     = 32
Maybe lat the user specify longer keys if they wish?

2024-10-10 18:34 UTC, MaartendeKruijf commented on auth/auth.go
> +func NewAuthenticator(cj cookies.ICookieJar, OIDCconfig *oidc.Config, OauthConfig *oauth2.Config, verifierProvider *oidc.Provider, skipTLSVerify bool, userClaims *UserClaimsConfig) *Authenticator {
New()

2024-10-10 18:34 UTC, MaartendeKruijf commented on auth/auth.go
> +func SetupOIDCAuthHandler() *Authenticator {
Why is this function here and the NewAuthenticator?

2024-10-10 18:34 UTC, MaartendeKruijf commented on auth/context.go
> +	groups, ok := permissions.([]string)
Please don't cast

2024-10-10 18:34 UTC, MaartendeKruijf commented on auth/context.go
> +func GetUserPermissions(gc *gin.Context) []string {
Permissions is not what is returned here. Either call the function GetUserAssignedGroups or actually return the permissions.

2024-10-10 18:34 UTC, MaartendeKruijf commented on auth/auth.go
> +func setupHTTPClient(skipTLS bool) *http.Client {
skipTLS is not correct is should be skipTlsValidation

2024-10-13 17:44 UTC, RabbITCybErSeC commented on auth/auth.go
> +	COOKIE_SECRET_KEY_LENGHT     = 32
This is already the strongest key: as specified in the gorilla session  docs:

It is recommended to use an authentication key with 32 or 64 bytes. The encryption key, if set, must be either 16, 24, or 32 bytes to select AES-128, AES-192, or AES-256 modes. 

https://pkg.go.dev/github.com/gorilla/sessions#NewCookieStore

2024-12-19 15:37 UTC, MaartendeKruijf requested changes

2024-12-19 15:37 UTC, MaartendeKruijf commented on go.mod
> +toolchain go1.23.1
Why is this added

2024-12-19 15:37 UTC, MaartendeKruijf commented on handlers/status.go
> +	return s.status.GetPongFromStatus("")
```suggestion
	bearerToken, _ := gauth_context.GetTokenFromContext(context)
	return s.status.GetPongFromStatus(bearerToken)
```

2024-12-19 15:37 UTC, MaartendeKruijf commented on routes/routes.go
> +	authEnabledToSoarca, _ := strconv.ParseBool(utils.GetEnv("AUTH_ENABLED", "false"))
Why split this?

2024-12-19 15:37 UTC, MaartendeKruijf commented on go.mod
> +	github.com/COSSAS/gauth v1.0.1
```suggestion
	github.com/COSSAS/gauth v1.0.2
```

2024-12-20 08:52 UTC, MaartendeKruijf requested changes

2024-12-20 08:52 UTC, MaartendeKruijf commented on handlers/oidc_handler.go
> +	// context.String(http.StatusFound, "")
remove unused code

2024-12-20 08:52 UTC, MaartendeKruijf commented on handlers/reporting.go
> +func (r *reportingHandler) fetchReports(context *gin.Context) ([]reporter.PlaybookExecutionReport, error) {
```suggestion
func (reporting *reportingHandler) fetchReports(context *gin.Context) ([]reporter.PlaybookExecutionReport, error) {
```

2024-12-20 08:52 UTC, MaartendeKruijf commented on handlers/status.go
>  func (s *statusHandler) HealthComponentHandler(context *gin.Context) {
```suggestion
func (status *statusHandler) HealthComponentHandler(context *gin.Context) {
```

2024-12-20 08:52 UTC, MaartendeKruijf commented on routes/routes.go
> +	status := soarca.NewStatus(utils.GetEnv("SOARCA_URI", "http://localhost:8080"), &http.Client{}, authEnabled)
Maybe wrap endpoint config into a struct so it can be passed easily.

2024-12-20 08:52 UTC, MaartendeKruijf commented on routes/routes.go
> +	}
unreachable if err != nil

2024-12-20 08:52 UTC, MaartendeKruijf commented on routes/routes.go
> +	}
Shouldn't this be handle in the called function

2024-12-20 08:52 UTC, MaartendeKruijf commented on routes/routes.go
>  }
Duplicate code

2024-12-20 13:43 UTC, MaartendeKruijf approved these changes

2024-12-20 13:43 UTC, merged