Feature/7 status indicator in dashboard
COSSAS/SOARCA-GUI pull request #8
Opened 2024-06-19 10:41 UTC by RabbITCybErSeC

2024-07-08 14:34 UTC, MaartendeKruijf requested changes

2024-07-08 14:34 UTC, MaartendeKruijf commented on public/public/styles.css
> -/*! tailwindcss v3.4.4 | MIT License | https://tailwindcss.com*/*,:after,:before{box-sizing:border-box;border:0 solid #e5e7eb}:after,:before{--tw-content:""}:host,html{line-height:1.5;-webkit-text-si
Add this file to .gitignore

2024-07-09 11:31 UTC, RabbITCybErSeC commented on public/public/styles.css
> -/*! tailwindcss v3.4.4 | MIT License | https://tailwindcss.com*/*,:after,:before{box-sizing:border-box;border:0 solid #e5e7eb}:after,:before{--tw-content:""}:host,html{line-height:1.5;-webkit-text-si
done

2024-07-09 11:55 UTC, MaartendeKruijf approved these changes

2024-07-09 11:56 UTC, merged